name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Preparing Linux Environment
      run: sudo apt-get update
    - name: Setting Up the Ubuntu Environment
      run: |
        # Install lightweight desktop (XFCE) and VNC server
        sudo apt-get install -y xfce4 xfce4-goodies tightvncserver
        
        # Create user (if not exists) and set password
        sudo useradd -m -s /bin/bash ${{ secrets.LINUX_USERNAME }} || true
        echo "${{ secrets.LINUX_USERNAME }}:${{ secrets.LINUX_USER_PASSWORD }}" | sudo chpasswd
        
        # Switch to the user and set up VNC
        sudo -u ${{ secrets.LINUX_USERNAME }} bash -c "
          # Set VNC password (using the same as user password for simplicity; change if needed)
          echo '${{ secrets.LINUX_USER_PASSWORD }}' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # Start VNC server on display :1 (port 5901 by default) with 1920x1080 resolution
          vncserver -geometry 1920x1080 :1
        "
        
        # Optional: Any other setup (e.g., Chrome headless if needed)
        # Add here if relevant, e.g., export CHROME_HEADLESS_CODE=${{ secrets.CHROME_HEADLESS_CODE }}
        
        # Install Bore (free tunneling tool)
        wget -q https://github.com/ekzhang/bore/releases/latest/download/bore-x86_64-unknown-linux-gnu.tar.gz
        tar -xzf bore-x86_64-unknown-linux-gnu.tar.gz
        sudo mv bore /usr/local/bin/
        
        # Start free Bore tunnel for VNC (port 5901, as VNC uses :1 by default; runs in background)
        # Bore will output the tunnel URL in logs (e.g., listening at bore.pub:xxxxx)
        # Connect with Remmina using VNC protocol to bore.pub:xxxxx
        bore local 5901 --to bore.pub &
    - name: Keep Running Ubuntu System and keepAlive
      run: sleep 6h
