name: Ubuntu ssh Virtual Machine
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Preparing Linux Environment
      run: sudo apt-get update --quiet
    - name: Setting Up the Ubuntu Environment
      run: |
        set -x  # Enable verbose logging to track progress
        
        # Install lightweight desktop (XFCE) and VNC server faster (skip recommends, combine)
        sudo apt-get install -y --no-install-recommends xfce4 xfce4-goodies tightvncserver
        
        # Create user and set password in parallel with other setup
        sudo useradd -m -s /bin/bash ${{ secrets.LINUX_USERNAME }} || true
        echo "${{ secrets.LINUX_USERNAME }}:${{ secrets.LINUX_USER_PASSWORD }}" | sudo chpasswd
        sudo usermod -aG sudo ${{ secrets.LINUX_USERNAME }}
        
        # Switch to the user and set up VNC (optimized)
        sudo -u ${{ secrets.LINUX_USERNAME }} bash -c "
          mkdir -p ~/.vnc
          echo '${{ secrets.LINUX_USER_PASSWORD }}' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          # Start VNC server with 1920x1080 (if slow, try 1280x720)
          vncserver -geometry 1920x1080 :1
        "
        
        # Optional: Any other setup (e.g., Chrome headless if needed)
        # Add here if relevant, e.g., export CHROME_HEADLESS_CODE=${{ secrets.CHROME_HEADLESS_CODE }}
        
        # Install Bore quickly (download and move in one go)
        wget -q https://github.com/ekzhang/bore/releases/latest/download/bore-x86_64-unknown-linux-gnu.tar.gz && \
        tar -xzf bore-x86_64-unknown-linux-gnu.tar.gz && \
        sudo mv bore /usr/local/bin/
        
        # Start free Bore tunnel for VNC (port 5901)
        bore local 5901 --to bore.pub &
    - name: Keep Running Ubuntu System and keepAlive
      run: sleep 6h
